### ISSUE TITLE
Parser doesn't support structs without field identifiers

### ISSUE THREAD

**Issue by phated** [creditkarma/thrift-parser-fork#6]
According to https://diwakergupta.github.io/thrift-missing-guide/, the field identifiers are required but the fixtures included with the Thrift library have some structs defined without identifiers.

I'm not sure which is correct.

**Comment by phated** [comment]
Based on https://thrift.apache.org/docs/idl#field, I believe the FieldID is optional

**Comment by ian-harshman-ck** [comment]
Dug into this a bit. Optional FieldIDs seem to be a relic of older versions of thrift. They have since been heavily deprecated.

Although the Apache generator spits out "non-specified field id" warnings, it will still generate code successfully - the generator assigns those fields negative ids, decrementing in the order they are encountered. If you add the `--strict` flag, though, it will error out. 

I wonder if we should make the parser strict by default. It's a really bad idea to omit FieldIDs from an IDL, and warnings may be too easily ignored.

**Comment by phated** [comment]
@nnance thoughts?  I'll hold off from merging the related PR until we discuss further.

**Comment by phated** [comment]
It looks like a fix landed for this upstream that just adds a `try/catch` around the ID read.  This means that the `id` property will be undefined in the AST and the numbering logic can be added into the compiler.
